fix missing builder scripts
Change-Id: I4bb25bfe78fbab741c56fa0dba3eb64b707becc1
Signed-off-by: Dhruvil Shah <dsdruvil8@gmail.com>

diff --git a/secondary/tests/ci/scripts/builder b/secondary/tests/ci/scripts/builder
--- a/secondary/tests/ci/scripts/builder
+++ b/secondary/tests/ci/scripts/builder
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+error_exit() {
+  echo "</pre><h3>Server build failed: $1</h3><pre>"
+  exit 2
+}
+
 FORCEX86=0
 if [ "$(echo $1 | tr 'A-Z' 'a-z')" = "-forcex86" ]; then
 	FORCEX86=1
